### ISSUE TITLE
OverflowError: Value is too large at simulated DS startup

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/SimulatorDS#14]
Hi Sergi,
I got strange `OverflowError: Value is too large` messages in the console when starting a simulated DS.

```
$ ./SimulatorDS.py RedPitaya_simu
In DynamicDS.CreateDynamicCommands(SimulatorDS/RedPitaya_simu)
class = SimulatorDS; classes = ['dserver/SimulatorDS/RedPitaya_simu', 'DServer', 'er/ca/rac.05-elr.01-rdp.01-simul', 'SimulatorDS']
devs = ['er/ca/rac.05-elr.01-rdp.01-simul']
In DynamicDS.CreateDynamicCommands(SimulatorDS/RedPitaya_simu.er/ca/rac.05-elr.01-rdp.01-simul): ["AcqOneShot = DevString('er/ca/rac.05-elr.01-rdp.01-simul/AcqOneShot')", "AcqStart = DevString('er/ca/rac.05-elr.01-rdp.01-simul/AcqStart')", "AcqStop = DevString('er/ca/rac.05-elr.01-rdp.01-simul/AcqStop')", "GeneStart = DevString('er/ca/rac.05-elr.01-rdp.01-simul/GeneStart')", "GeneStop = DevString('er/ca/rac.05-elr.01-rdp.01-simul/GeneStop')", "Help = DevString('er/ca/rac.05-elr.01-rdp.01-simul/Help')", "Reset = DevString('er/ca/rac.05-elr.01-rdp.01-simul/Reset')", "evaluateFormula = DevString(ARGS and 'er/ca/rac.05-elr.01-rdp.01-simul/evaluateFormula')", "getDynamicConfig = DevString('er/ca/rac.05-elr.01-rdp.01-simul/getDynamicConfig')", 'getMemUsage = DevDouble(1.0 * (1+2*sin((int(PROPERTY("OFFSET"))+t)%3.14)))', 'processEvents = DevLong(int(PROPERTY("OFFSET"))+randint(0,10) * 1.0)', "setPauseEvents = DevString(ARGS and 'er/ca/rac.05-elr.01-rdp.01-simul/setPauseEvents')", "updateDynamicAttributes = DevString('er/ca/rac.05-elr.01-rdp.01-simul/updateDynamicAttributes')"]
list2lines: done
Dynamic Command <type 'Boost.Python.class'>.Help Already Exists, skipping!!!
Dynamic Command <type 'Boost.Python.class'>.evaluateFormula Already Exists, skipping!!!
Dynamic Command <type 'Boost.Python.class'>.getDynamicConfig Already Exists, skipping!!!
Dynamic Command <type 'Boost.Python.class'>.getMemUsage Already Exists, skipping!!!
Dynamic Command <type 'Boost.Python.class'>.updateDynamicAttributes Already Exists, skipping!!!
Out of DynamicDS.CreateDynamicCommands(SimulatorDS/RedPitaya_simu)
In DynamicDSClass.__new__(<class '__main__.SimulatorDSClass'>): updating properties
DynamicSpectrumSize property NOT found in database
In SimulatorDSClass  constructor
IN SimulatorDS.__INIT__
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
UseTaurus = False
< ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In  er/ca/rac.05-elr.01-rdp.01-simul ::init_device()
################################################################################
list2lines: done
list2lines: done
list2lines: done
DynamicDS().open_file(/home/gauron/SimulatorDS/SimulatorDS_attributes.txt)
Out of  er/ca/rac.05-elr.01-rdp.01-simul ::init_device()
In DynamicDSClass.dyn_attr([SimulatorDS(er/ca/rac.05-elr.01-rdp.01-simul)])
DynamicDS.dyn_attr( ... ), finished. Attributes ready to accept request ...
list2lines: done
Traceback (most recent call last):
  File "/home/gauron/.local/lib/python2.7/site-packages/fandango/dynamic.py", line 1128, in read_dyn_attr
    attr.set_value_date_quality(result,date,quality)
OverflowError: Value is too large.

Traceback (most recent call last):
  File "/home/gauron/.local/lib/python2.7/site-packages/fandango/dynamic.py", line 1128, in read_dyn_attr
    attr.set_value_date_quality(result,date,quality)
OverflowError: Value is too large.

Traceback (most recent call last):
  File "/home/gauron/.local/lib/python2.7/site-packages/fandango/dynamic.py", line 1128, in read_dyn_attr
    attr.set_value_date_quality(result,date,quality)
OverflowError: Value is too large.
[...]
```

Is there a way to check from which attribute it occurs? Did you already encounter this kind of message in this context?

Thank you.

**Comment by sergirubio** [comment]
It may occur because I'm not taking into account yet size constraints in array/image attributes
Could you attach the .pck file so I can try to replicate the error?

**Comment by sergirubio** [comment]
I didn't have time to finish the patch, but I have verified that big array attributes also give problems to SimulatorDS

Please, try to verify SimulatorDS on an smaller device and i'll try to publish a patch during the next week

**Comment by PhilLAL** [comment]
Hi Sergi,
thank you very much for taking time to check. Please find the PCK file [here](https://owncloud.lal.in2p3.fr/index.php/s/6db3l6vNvgVoing).

For now, I did not encountered this issue on other DS at this time but I'll check asap.

**Comment by sergirubio** [comment]
I'll try to commit a patch on monday, basically limiting the size of arrays to be loaded using a SimulatorDS class property.
Does this solution match your needs?

**Comment by PhilLAL** [comment]
Thank you. I'm not sure what limit should be defined, and I imagine this limit will be statically defined.
But for sure, a value which could be changed will be useful if it is needed to change to a higher value :)

**Comment by PhilLAL** [comment]
I tested again with new SimulatorDS repo content, it does not crash as described in first post.
Display is strange but perhaps is it linked to some other issue. I think this one can be closed.
Thank you again for this solution. :)
