### ISSUE TITLE
instance name used to launch simulation instance

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/SimulatorDS#5]
Hi Sergi,
going further into my tests, I followed instructions from https://github.com/tango-controls/SimulatorDS/blob/master/doc/gen_simulation.rst

- I generated the simulation instance from the file «~/test-attributes-tangoserver2-Maquette-Vide.pck» on server tango9.
This ~/test-attributes-tangoserver2-Maquette-Vide.pck file was built from a fandango output file which only contained one device: maquette/vide/vacuumvalve1

For information, here is the output of the instance generation:

```
tango9@tango9:~/SimulatorDS$> ./gen_simulation.py load ~/SimulatorDS/essai/test-attributes-tangoserver2-Maquette-Vide-VacuumValve1.pck tango9
Welcome to the generic simulation script
--------------------------------------------------------------------------------
create_simulators:('/home/tango9/SimulatorDS/essai/test-attributes-tangoserver2-Maquette-Vide-VacuumValve1.pck', '', '/home/tango9/SimulatorDS/essai/', {}, 'tango9')
Property files do not exist yet,
Do you want to generate them? (y/n)y
generate_class_properties:/home/tango9/SimulatorDS/essai/test-attributes-tangoserver2-Maquette-Vide-VacuumValve1.pck
classes in /home/tango9/SimulatorDS/essai/test-attributes-tangoserver2-Maquette-Vide-VacuumValve1.pck are: ['VacuumValve']
Do you want to filter out some classes? [PyStateComposer]

Writing VacuumValve attributes ([9])

CompressedAirFault = DevBoolean(randint(0,1))
CptOpenClose = DevShort(int(PROPERTY("OFFSET"))+randint(0,10) * choice([0] or [0]))
Remote = DevBoolean(randint(0,1))
combinedState = DevShort(int(PROPERTY("OFFSET"))+randint(0,10) * choice([386] or [0]))
fault = DevBoolean(randint(0,1))
isIncomingSecurityEnabled = DevBoolean(randint(0,1))
isInterlocked = DevBoolean(randint(0,1))
maxTime = DevDouble(VAR('maxTime',default=3.0 * (1+2*sin((int(PROPERTY("OFFSET"))+t)%3.14))) if not WRITE else VAR('maxTime',VALUE))
memorizedFault = DevBoolean(randint(0,1))

Writing VacuumValve commands ([5])

Close = DevString('maquette/vide/vacuumvalve1/Close')
DisableIncomingSecurity = DevString('maquette/vide/vacuumvalve1/DisableIncomingSecurity')
EnableIncomingSecurity = DevString('maquette/vide/vacuumvalve1/EnableIncomingSecurity')
FaultAck = DevString('maquette/vide/vacuumvalve1/FaultAck')
Open = DevString('maquette/vide/vacuumvalve1/Open')

Writing VacuumValve states ([3])

MOVING=t%randint(15,30)>randint(1,15)
ALARM=t%randint(1,30)<randint(1,6)
ON=1
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
1 devices in /home/tango9/SimulatorDS/essai/test-attributes-tangoserver2-Maquette-Vide-VacuumValve1.pck: ['maquette/vide/vacuumvalve1']
Enter a filter for device names: [*/*/*]
Enter your instance name for the simulated server (use "instance-" to use multiple instances):VacuumValve1-simulation
Keep original Class names?yes
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
SimulatorDS/VacuumValve1-simulationVacuumValve:maquette/vide/vacuumvalve1 , "VacuumValve" => VacuumValve_sim 
writing ... <class 'fandango.objects.Struct'>(maquette/vide/vacuumvalve1)
Updating 0 Devices ...
1 devices creation done
('maquette/vide/vacuumvalve1', 'dserver/databaseds/2')
['load'] done
```

Following the doc, I started simulation instance with name "VacuumValve1-simulation" as I named the instance, and I got an erreur

```
tango9@tango9:~/SimulatorDS$> ./gen_simulation.py play VacuumValve1-simulation
Welcome to the generic simulation script
--------------------------------------------------------------------------------
run_dynamic_server:VacuumValve1-simulation
Scipy not available
The device server SimulatorDS/VacuumValve1-simulation is not defined in database. Exiting!
```

- I installed Scipy with `pip install scipy` and run again both steps (in fact, I ran last step and since it failed, I ran both steps just in case).
Here are the output:

```
tango9@tango9:~/SimulatorDS$> ./gen_simulation.py load ~/SimulatorDS/essai/test-attributes-tangoserver2-Maquette-Vide-VacuumValve1.pck tango9
Welcome to the generic simulation script
--------------------------------------------------------------------------------
create_simulators:('/home/tango9/SimulatorDS/essai/test-attributes-tangoserver2-Maquette-Vide-VacuumValve1.pck', '', '/home/tango9/SimulatorDS/essai/', {}, 'tango9')
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
1 devices in /home/tango9/SimulatorDS/essai/test-attributes-tangoserver2-Maquette-Vide-VacuumValve1.pck: ['maquette/vide/vacuumvalve1']
Enter a filter for device names: [*/*/*]
1 devices already exist: ['maquette/vide/vacuumvalve1']
Do you want to override existing properties? (y/n)y
Enter your instance name for the simulated server (use "instance-" to use multiple instances):VacuumValve1-simulation
```
Here is where I named my instance **VacuumValve1-simulation**.
```
Keep original Class names?yes
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
SimulatorDS/VacuumValve1-simulationVacuumValve:maquette/vide/vacuumvalve1 , "VacuumValve" => VacuumValve_sim 
```
Here is where output give the real name of the instance I should use ***VacuumValve1-simulationVacuumValve***.
```
writing ... <class 'fandango.objects.Struct'>(maquette/vide/vacuumvalve1)
Updating 0 Devices ...
1 devices creation done
('maquette/vide/vacuumvalve1', 'dserver/databaseds/2')
['load'] done

tango9@tango9:~/SimulatorDS$ ./gen_simulation.py play VacuumValve1-simulation
Welcome to the generic simulation script
--------------------------------------------------------------------------------
run_dynamic_server:VacuumValve1-simulation
The device server SimulatorDS/VacuumValve1-simulation is not defined in database. Exiting!
```

So after a bit wondering, I saw in jive the instance name is not "VacuumValve1-simulation" as I named it when asked (see upside in bold) but "VacuumValve1-simulationVacuumValve" (see upside in bold and italic) which gave me the answer:
```tango9@tango9:~/SimulatorDS$ ./gen_simulation.py play VacuumValve1-simulationVaccumValve```

- I understand the instance name to launch will be the instance name given concatenated to the Class name.
I did not pushed my tests to check the behaviour if several devices with several Classes are exported through fandango...

Perhaps doc could include a few informations about scipy dependency and the name of instance which seems to be followed by the Class name (if I understand well) ?
I can also propose a PR to update the output of the gen_simulation common options if you think it could be useful.
Regards.

**Comment by sergirubio** [comment]
Thanks for your feedback, I've been reviewing the workflow and certainly 
all the steps requiring temporary files are not clear enough, and polute 
the database with unnecessary information.

I'm finally finished with maintenance tasks and tomorrow I have the 
whole morning to work on simulatords, so if you want to send me your 
proposal regarding gen_simulation options I can study it and try to 
apply it.

Thanks for your patience, I was busy with some urgent updates in other 
projects.

Sergi Rubio

**Comment by PhilLAL** [comment]
Thank you Sergi.
For output of gen_simulation, I think several possibilities exists:
1. Make `gen_simulation export` using the exact instance name entered as answer to `gen_simulation export` question (then in my instance example, the instance name entered to `gen_simulation export` question should be `VacuumValve1-simulation` and the command for playing would be `gen_simulation play VacuumValve1-simulation`)
2. Make `gen_simulation play` completing the instance name entered to `gen_simulation export` question as option to make it match to the real instance name (then in my instance example, the instance name entered to `gen_simulation export` question should be `VacuumValve1-simulation` and the command for playing would be `gen_simulation play VacuumValve1-simulation` but internally, instance name would be `VacuumValve1-simulationVacuumValve`)
3. Make it clear that the instance name to give to `gen_simulation play` will not be the given name of the instance (then in my instance example, the instance name entered to `gen_simulation export` question should be `VacuumValve1-simulation` and the command for playing would be `gen_simulation play VacuumValve1-simulationVacuumValve`)

I would rather choose solution 1 since it will use the same instance name everywhere, which will avoid to mislead the user, but I am not sure of what it implies into the code.

**Comment by PhilLAL** [comment]
I'm not sure this was what you mean, let me know if I can detail some point, of even if this is not a good solution. :)

**Comment by sergirubio** [comment]
Hi PhiLAL,

The first option (using same instance name as entered by the user) is of 
course the more clear.

I expected some comments regarding the workflow, but don't worry, I'm 
working on it

Sergi

**Comment by PhilLAL** [comment]
Ok, thanks.
For the workflow and files, it seems to me an option could perhaps launch fandango export and then automatically export the simulated device, but I lake experience using these two commands to check in detail.
I will investigate this and let you know if I think of something.

**Comment by sergirubio** [comment]
Hi PhiLAL, I refactored the gen_simulation script to have much clearer steps and questions asked.

Sorry for not understanding your question at the beginning, I haven't used the option with a "-" for a while, sorry.

Please, check the new recipe from develop and tell me if the new workflow seems more straightforward:

https://github.com/tango-controls/SimulatorDS/blob/develop/doc/Generate_Simulations.rst

Thanks for your help testing it!

**Comment by PhilLAL** [comment]
Thank you for this explanation file, the use of SimulatorDS seems much more understandable. :)


In Generate_Simulations.rst, you write ```The declaration of formulas can be done directly by user (see SimulatorDS documentation)```.
This will help a lot our users which will use these DS.


Here are a few general comments about https://github.com/tango-controls/SimulatorDS/blob/develop/doc/Generate_Simulations.rst file :

- line 65 and 77 : delete space before "::"
- line 67 : return usage if called with only one device and one pickle file (condition "en(args)<2" raised on line 515)
Should it be  ```gen_simulation.py export sr02/vc/eps-plc-01 sr02/vc/mir-01 sr02_plcs.pck``` ?

- line 69, the GUI source files should be explained (Taurus GUI only ?)
- line 119-124: questions (when default answer choosen) are:
```
Enter a filter for device names: [*/*/*]
Enter your instance name for the simulated servers:
Do you want to split Simulators in several servers,one for each class (y/[n])?
Keep original Class names (if not, all devices will be generated as SimulatorDS) (y/[n])
Enter your server name (SimulatorDS/DynamicDS): [SimulatorDS]
Creating new Tango Device X/Y/Z of class SimulatorDS in server SimulatorDS/<INSTANCE>
()
	Added property: [...]
X/Y/Z attribute formulas will be loaded from:
	<...>/SimulatorDS/<INSTANCE>_attributes.txt

Do you want to copy them also to Tango DB so you can tune them manually ([y]/n)?
```
Tests :

If I launch `gen_simulation.py` with a file using a relative path, I got an error:
```
$ ./gen_simulation.py load essai/Maquette-diag-RP2-0.pck tango9

Welcome to the generic simulation script
--------------------------------------------------------------------------------
create_simulators:('essai/Maquette-diag-RP2-0.pck', '', '/home/tango9/SimulatorDS/essai/', {}, 'tango9')
()
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
1 devices in essai/Maquette-diag-RP2-0.pck: ['maquette/diag/rp2-0']

Enter a filter for device names: [*/*/*]

Enter your instance name for the simulated servers:RP2_0    

Do you want to split Simulators in several servers,one for each class (y/[n])? 

Keep original Class names (if not, all devices will be generated as SimulatorDS) (y/[n])? 

Enter your server name (SimulatorDS/DynamicDS): [SimulatorDS]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


********************************************************************************
Checking rp2-0 Tango Class ... 
generate_class_properties:essai/Maquette-diag-RP2-0.pck
Traceback (most recent call last):
  File "./gen_simulation.py", line 557, in <module>
    main(args)
  File "./gen_simulation.py", line 539, in main
    domains=args[2:] and eval(args[1]) or {})
  File "./gen_simulation.py", line 361, in create_simulators
    generate_class_properties(filein,classnames=[orgklass])
  File "./gen_simulation.py", line 165, in generate_class_properties
    devs = pickle.load(open(filein))
IOError: [Errno 2] No such file or directory: 'essai/Maquette-diag-RP2-0.pck
```
I understand it is because path is defined at line 265 as relatively to filein which should so be passed completed with directory where is launched gen_simulation.py as prefix 

IF I launch gen_simulation.py with an absolute path, I got an error later when generating attribute file: 

```
$ ./gen_simulation.py load ~/SimulatorDS/essai/Maquette-diag-RP2-0.pck tango9

Welcome to the generic simulation script
--------------------------------------------------------------------------------
create_simulators:('/home/tango9/SimulatorDS/essai/Maquette-diag-RP2-0.pck', '', '/home/tango9/SimulatorDS/essai/', {}, 'tango9')
()
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
1 devices in /home/tango9/SimulatorDS/essai/Maquette-diag-RP2-0.pck: ['maquette/diag/rp2-0']

Enter a filter for device names: [*/*/*]

Enter your instance name for the simulated servers:redpitaya

Do you want to split Simulators in several servers,one for each class (y/[n])? 

Keep original Class names (if not, all devices will be generated as SimulatorDS) (y/[n])? 

Enter your server name (SimulatorDS/DynamicDS): [SimulatorDS]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


********************************************************************************
Checking rp2-0 Tango Class ... 
generate_class_properties:/home/tango9/SimulatorDS/essai/Maquette-diag-RP2-0.pck

********************************************************************************
SimulatorDS/redpitaya:maquette/diag/rp2-0 , "rp2-0" => SimulatorDS 
Creating new Tango Device maquette/diag/rp2-0 of class SimulatorDS in server SimulatorDS/redpitaya
()
	Added property: maquette/diag/rp2-0/ScaleChannelA [1]
	Added property: maquette/diag/rp2-0/ScaleChannelB [1]
	Added property: maquette/diag/rp2-0/LoadFromFile [51]
maquette/diag/rp2-0 attribute formulas will be loaded from:
	/home/tango9/SimulatorDS/essai/rp2-0_attributes.txt

Do you want to copy them also to Tango DB so you can tune them manually ([y]/n)? 
Unable to configure maquette/diag/rp2-0(rp2-0) properties 
Traceback (most recent call last):
  File "./gen_simulation.py", line 396, in create_simulators
    path+'%s_attributes.txt'%t.dev_class,path)
  File "./gen_simulation.py", line 389, in load_prop_from_file
    v = filter(bool,map(str.strip,open(f).readlines()))
IOError: [Errno 2] No such file or directory: '/home/tango9/SimulatorDS/essai/rp2-0_attributes.txt'
()
Updating 0 Devices ...
1 devices creation done
('maquette/diag/rp2-0', 'dserver/databaseds/2')


To start the simulators, use any of these commands:

	python gen_simulation.py play redpitaya

	SimulatorDS redpitaya

['load'] done
```

If I move the pck file into the SimulatorDS directory, load works only with `python gen_simulation.py play VacuumValve`. Launching it with SimulatorDS.py VacuumValve give following output:
```
$ ./SimulatorDS.py VacuumValve_omniORB: Warning: the local loop back interface (127.0.0.1)
is the only address available for this server.
The device server SimulatorDS/VacuumValve_ is not defined in database. Exiting!
```

I'll continue my tests next week.

**Comment by sergirubio** [comment]
Hi PhiLAL, in your past example ... was /home/tango9/SimulatorDS/essai/rp2-0_attributes.txt properly generated?

**Comment by sergirubio** [comment]
I have pushed some changes with your suggestions to gen_simulation code and docs

**Comment by PhilLAL** [comment]
> Hi PhiLAL, in your past example ... was /home/tango9/SimulatorDS/essai/rp2-0_attributes.txt properly generated?

I currently do not have access to the device to check, but I'll do this asap. However, I checked with another device and launching `SimulatorDS.py VacuumValve` works so it is probably an error due to the device export.

Thank you for these additions.

**Comment by PhilLAL** [comment]
Hi again Sergi,
I continued my tests with following steps (I resumed some 0.00 by [...]
```
$ gen_simulation.py load redpitaya.pck 134.158.75.81

Executing the generic simulation script ...
--------------------------------------------------------------------------------
create_simulators:('redpitaya.pck', '', '/home/gauron/tmp/', {}, '134.158.75.81')
()
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
1 devices in redpitaya.pck: ['er/ca/rac05-elr.01-rdp1']

Enter a filter for device names: [*/*/*]

Enter your instance name for the simulated servers:RedPitaya

Do you want to split Simulators in several servers,one for each class (y/[n])? 

Keep original Class names (if not, all devices will be generated as SimulatorDS) (y/[n])? 

Enter your server name (SimulatorDS/DynamicDS): [SimulatorDS]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


********************************************************************************
Checking RedPitaya Tango Class ... 
generate_class_properties:redpitaya.pck
er/ca/rac05-elr.01-rdp1 RedPitaya Waveform_ChB fandango.Struct({'color': Lime,'display_unit': No display unit,'writable': READ,'standard_unit': No standard unit,'quality': ATTR_VALID,'unit': ,'string':   0.00,  0.00,  [...]  0.00,  0.00,'max_dim_y': 0,'max_dim_x': 16384,'label': Waveform_ChB,'max_value': Not specified,'min_alarm': Not specified,'events': fandango.Struct({'per_event': {'extensions': '[]', 'period': '1000'},'ch_event': {'rel_change': 'Not specified', 'extensions': '[]', 'abs_change': 'Not specified'},'arch_event': {'archive_period': 'Not specified', 'archive_abs_change': 'Not specified', 'archive_rel_change': 'Not specified', 'extensions': '[]'},}),'description': ,'data_type': DevFloat,'format': %6.2f,'max_alarm': Not specified,'min_value': Not specified,'device': er/ca/rac05-elr.01-rdp1,'enum_labels': [],'name': Waveform_ChB,'database': 192.168.209.252:20000,'datatype': DevFloat,'data_format': SPECTRUM,'value': [0.0, 0.0, [...] 0.0, 0.0],'polling': 0,'time': 1535109525.05,'alarms': {'delta_t': 'Not specified', 'max_alarm': 'Not specified', 'min_warning': 'Not specified', 'extensions': '[]', 'delta_val': 'Not specified', 'min_alarm': 'Not specified', 'max_warning': 'Not specified'},'model': 192.168.209.252:20000/er/ca/rac05-elr.01-rdp1/Waveform_ChB,})
er/ca/rac05-elr.01-rdp1 RedPitaya Waveform_ChA fandango.Struct({'color': Lime,'display_unit': No display unit,'writable': READ,'standard_unit': No standard unit,'quality': ATTR_VALID,'unit': ,'string':   0.00,  0.00,   nan,296420450720224674891025088512.00,79327539388858010780491752432205824.00,4471110659658645241856.00,72727909806465760624640.00,4544506596204846836597584297984.00,  0.00,3103570243071974666487726080.00,18394623951250789884755968.00,189371644558519872520192.00,184982803827266682880.00,18319373917566605589479424.00,72151422032564572913664.00,1142611228620170281450242264006656.00,4741805103354683739853394280448.00,3690487036497333432877056.00,3683464879843149279657984.00,  0.00,  0.00,  [...],  0.00,  0.00,'max_dim_y': 0,'max_dim_x': 16384,'label': Waveform_ChA,'max_value': Not specified,'min_alarm': Not specified,'events': fandango.Struct({'per_event': {'extensions': '[]', 'period': '1000'},'ch_event': {'rel_change': 'Not specified', 'extensions': '[]', 'abs_change': 'Not specified'},'arch_event': {'archive_period': 'Not specified', 'archive_abs_change': 'Not specified', 'archive_rel_change': 'Not specified', 'extensions': '[]'},}),'description': ,'data_type': DevFloat,'format': %6.2f,'max_alarm': Not specified,'min_value': Not specified,'device': er/ca/rac05-elr.01-rdp1,'enum_labels': [],'name': Waveform_ChA,'database': 192.168.209.252:20000,'datatype': DevFloat,'data_format': SPECTRUM,'value': [0.0, 0.0, 'nan', 2.9642045072022467e+29, 7.932753938885801e+34, 4.471110659658645e+21, 7.272790980646576e+22, 4.544506596204847e+30, 0.0, 3.1035702430719747e+27, 1.839462395125079e+25, 1.8937164455851987e+23, 1.8498280382726668e+20, 1.8319373917566606e+25, 7.215142203256457e+22, 1.1426112286201703e+33, 4.741805103354684e+30, 3.6904870364973334e+24, 3.6834648798431493e+24, 0.0, 0.0, [...], 0.0, 0.0],'polling': 0,'time': 1535109524.0,'alarms': {'delta_t': 'Not specified', 'max_alarm': 'Not specified', 'min_warning': 'Not specified', 'extensions': '[]', 'delta_val': 'Not specified', 'min_alarm': 'Not specified', 'max_warning': 'Not specified'},'model': 192.168.209.252:20000/er/ca/rac05-elr.01-rdp1/Waveform_ChA,})

Writing RedPitaya attributes ([76])


Writing RedPitaya commands ([6])


Writing RedPitaya states ([3])


********************************************************************************
SimulatorDS/RedPitaya:er/ca/rac05-elr.01-rdp1 , "RedPitaya" => SimulatorDS 
Creating new Tango Device er/ca/rac05-elr.01-rdp1 of class SimulatorDS in server SimulatorDS/RedPitaya
()
	Added property: er/ca/rac05-elr.01-rdp1/ScaleChannelA [1]
	Added property: er/ca/rac05-elr.01-rdp1/ScaleChannelB [1]
	Added property: er/ca/rac05-elr.01-rdp1/LoadFromFile [41]
er/ca/rac05-elr.01-rdp1 attribute formulas will be loaded from:
	/home/gauron/tmp/RedPitaya_attributes.txt

Do you want to copy them also to Tango DB so you can tune them manually ([y]/n)? 
	Added property: er/ca/rac05-elr.01-rdp1/DynamicAttributes [76] from /home/gauron/tmp/RedPitaya_attributes.txt
	Added property: er/ca/rac05-elr.01-rdp1/DynamicCommands [6] from /home/gauron/tmp/RedPitaya_commands.txt
	Added property: er/ca/rac05-elr.01-rdp1/DynamicStates [3] from /home/gauron/tmp/RedPitaya_states.txt
Updating 0 Devices ...
1 devices creation done
('er/ca/rac05-elr.01-rdp1', 'controller/dummycountertimercontroller/ctctrl03')


To start the simulators, use any of these commands:

	python gen_simulation.py play RedPitaya

	SimulatorDS RedPitaya



['load'] done
```
Then I launched the DS:
```
$ SimulatorDS RedPitaya
Launching /usr/local/lib/python2.7/dist-packages/fandango/SimulatorDS RedPitaya at 
run detached
screen -dm -S SimulatorDS-RedPitaya python /usr/local/lib/python2.7/dist-packages/fandango/SimulatorDS.py RedPitaya
```
I noticed it calls a specific `/usr/local/lib/python2.7/dist-packages/fandango/SimulatorDS.py`, but SimulatorDS.py is not in the directory.

Just to check, while launching `atkpanel er/ca/rac05-elr.01-rdp1` and got following error:
```
atkpanel RedPitaya
AtkPanel: Cannot connect to the device.
AtkPanel: Check the device name you entered;
AtkPanel: Application aborted....
AtkPanel: Connection Exception : Severity: PANIC
Origin: Connection(er/ca/rac05-elr.01-rdp1)
Description: er/ca/rac05-elr.01-rdp1 Not Exported !
Reason: TangoApi_DEVICE_NOT_EXPORTED
Severity: ERROR
Origin: Connection.build_connection(er/ca/rac05-elr.01-rdp1)
Description: Cannot import er/ca/rac05-elr.01-rdp1
Reason: TangoApi_CANNOT_IMPORT_DEVICE
```

One possible cause is that the computer on which I tried to create this instance is TANGO8 while the original DS runs on TANGO9. I think remembering something about this but I am not sure...

I tried it on a Tango9 VM and it worked well.
Is there a way to install an image of a captured DS on a TANGO8 server onto a TANGO9 server ?

**Comment by sergirubio** [comment]
Hi,

Try to run this code in the same machine were the device is running:

ipython
import fandango
fandango.check_device('your/device/name'))
fandango.check_attribute('your/device/name/status').value

**Comment by PhilLAL** [comment]
Following your instructions on my TANGO**8** server, it seems device is not well created, I got following output:

```
$ SimulatorDS RedPitaya
Launching /usr/local/lib/python2.7/dist-packages/fandango/SimulatorDS RedPitaya at 
run detached
screen -dm -S SimulatorDS-RedPitaya python /usr/local/lib/python2.7/dist-packages/fandango/SimulatorDS.py RedPitaya

$ ipython
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
Type "copyright", "credits" or "license" for more information.

IPython 5.5.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import fandango

In [2]: fandango.check_device('er/ca/rac05-elr.01-rdp1'))
  File "<ipython-input-2-7d011b27087b>", line 1
    fandango.check_device('er/ca/rac05-elr.01-rdp1'))
                                                    ^
SyntaxError: invalid syntax


In [3]: fandango.check_device('er/ca/rac05-elr.01-rdp1')
Out[3]: False
```

```
$ pip list |grep  fandango
fandango                           13.9.0
```

**Comment by PhilLAL** [comment]
By the way, I saw the instance name is now exactly the one entered by the user.
One just have to be sure to enter an instance name and not pressing enter at each step of generation, otherwise instance seems to be null. :)

**Comment by sergirubio** [comment]
Hi PhilLAL,

Can you check again if this issue is solved with latest versions?

Sergi

**Comment by PhilLAL** [comment]
Hi Sergi,
thank you for this fix, it seems to work! :)

```
In [1]: import fandango 

In [2]: fandango.check_device('er/ca/rac.05-elr.01-rdp.01')
Out[2]: 'ON'

In [3]: fandango.check_attribute('er/ca/rac.05-elr.01-rdp.01/status').value
Out[3]: 'The device is in ON state.'
```
